version: '3.3'


services:
  node_backend:
    container_name: node_server
    image: node_server
    build: 
      context: .
    ports:
      - '4000:4000'
    environment:
      - EXTERNAL_PORT=4000
      - PGDATABASE=chat2
      - PGUSER=postgres
      - PGPASSWORD=ass_e1
      - PGHOST=node_db
    depends_on:
      node_db: 
        condition: service_healthy

  node_db:
    container_name: node_db 
    image: "postgres:12.4"
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=ass_e1
    - POSTGRES_DB=chat2
    volumes:
    - /var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres


